//Get

// [
//     {
//       "_id": "64f1a2c5a9b1f3a6d8c12345",
//       "name": "iPhone 14",
//       "price": 1200,
//       "category": "Electronics",
//       "inStock": true,
//       "__v": 0,
//       "createdAt": "2025-08-28T10:15:30.123Z",
//       "updatedAt": "2025-08-28T10:15:30.123Z"
//     },
//     {
//       "_id": "64f1a2c5a9b1f3a6d8c67890",
//       "name": "Nike Shoes",
//       "price": 150,
//       "category": "Footwear",
//       "inStock": false,
//       "__v": 0,
//       "createdAt": "2025-08-29T14:22:11.456Z",
//       "updatedAt": "2025-08-29T14:22:11.456Z"
//     }
//   ]

// {
//   "success": true,
//   "data": [
//     {
//       "_id": "64f1a2c5a9b1f3a6d8c12345",
//       "name": "iPhone 14",
//       "price": 1200,
//       "category": "Electronics",
//       "inStock": true,
//       "__v": 0,
//       "createdAt": "2025-08-28T10:15:30.123Z",
//       "updatedAt": "2025-08-28T10:15:30.123Z"
//     },
//     {
//       "_id": "64f1a2c5a9b1f3a6d8c67890",
//       "name": "Nike Shoes",
//       "price": 150,
//       "category": "Footwear",
//       "inStock": false,
//       "__v": 0,
//       "createdAt": "2025-08-29T14:22:11.456Z",
//       "updatedAt": "2025-08-29T14:22:11.456Z"
//     }
//   ]
// }

// {
//   "success": false,
//   "message": "Server error"
// }


//create 

// {
//   "name": "iPhone",
//   "price": "1000",
//   "image": "https://..."
// }

// {
//   "success": true,
//   "data": {
//     "_id": "64fa9b7a1c2d5b3f5d123456",// generated by MongoDB/Mongoose
//     "name": "iPhone",
//     "price": "1000",
//     "image": "https://...",
//     "__v": 0, // mongoose version key (default)
//     "createdAt": "2025-09-01T06:15:45.789Z",
//     "updatedAt": "2025-09-01T06:15:45.789Z"
//   }
// }


//PUT /api/products/64fa9b7a1c2d5b3f5d123456
// {                                     
//   "name": "iPhone 16",
//   "price": "1200",
//   "image": "https://..."
// } 

// {
//   "success": true,
//   "data": {
//     "_id": "64fa9b7a1c2d5b3f5d123456",
//     "name": "iPhone 16",
//     "price": "1200",
//     "image": "https://...",
//     "__v": 0,
//     "createdAt": "2025-09-01T06:15:45.789Z",
//     "updatedAt": "2025-09-01T06:20:12.345Z"
//   }
// }

// {
//   "success": false,
//   "message": "Invalid product ID"
// }

// {
//   "success": false,
//   "message": "Product not found"
// }
 
//Delete /api/products/64fa9b7a1c2d5b3f5d123456
// {
//   "success": true,
//   "message": "Product deleted successfully"
// }

// {
//   "success": false,
//   "message": "Invalid product ID"
// } 
// {
//   "success": false,
//   "message": "Product not found"
// }
